In [54]:
import pandas as pd
import numpy as np

In [55]:
data = pd.read_csv("Churn_Modelling.csv")
data.head(5)
input_data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [56]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
##Lable Encode the Gender data
label_encoder=LabelEncoder()
input_data['Gender']=label_encoder.fit_transform(input_data["Gender"])
print(input_data)

      CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1
1             608     Spain       0   41       1   83807.86              1
2             502    France       0   42       8  159660.80              3
3             699    France       0   39       1       0.00              2
4             850     Spain       0   43       2  125510.82              1
...           ...       ...     ...  ...     ...        ...            ...
9995          771    France       1   39       5       0.00              2
9996          516    France       1   35      10   57369.61              1
9997          709    France       0   36       7       0.00              1
9998          772   Germany       1   42       3   75075.31              2
9999          792    France       0   28       4  130142.79              1

      HasCrCard  IsActiveMember  EstimatedSalary  Exited
0             1               1        101348.88       1
1             0               1        112542.58       0
2             1               0        113931.57       1
3             0               0         93826.63       0
4             1               1         79084.10       0
...         ...             ...              ...     ...
9995          1               0         96270.64       0
9996          1               1        101699.77       0
9997          0               1         42085.58       1
9998          1               0         92888.52       1
9999          1               0         38190.78       0

[10000 rows x 11 columns]

In [ ]:
## One Hot Encoding for geodata
one_hot_encoder = OneHotEncoder()
geo_encoded = one_hot_encoder.fit_transform(input_data[["Geography"]]).toarray()
column_names = one_hot_encoder.get_feature_names_out(["Geography"])

In [58]:
input_data = input_data.drop(["Geography"], axis=1)
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,42,2,0.00,1,1,1,101348.88,1
1,608,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,39,1,0.00,2,0,0,93826.63,0
4,850,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,0,36,7,0.00,1,0,1,42085.58,1
9998,772,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,0,28,4,130142.79,1,1,0,38190.78,0

In [66]:
# convert encoded data to dataframe
encoded_df = pd.DataFrame(geo_encoded, columns=column_names, index=input_data.index)

##Combine the data
input_data_df = pd.concat([input_data, encoded_df], axis=1)
input_data_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,"(Geography_France,)","(Geography_Germany,)","(Geography_Spain,)"
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [71]:
##Split data into dependent and independent parameters

X = input_data_df.drop("EstimatedSalary",axis=1)
y = input_data_df["EstimatedSalary"]

print(X)
print(y)

      CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1
1             608       0   41       1   83807.86              1          0
2             502       0   42       8  159660.80              3          1
3             699       0   39       1       0.00              2          0
4             850       0   43       2  125510.82              1          1
...           ...     ...  ...     ...        ...            ...        ...
9995          771       1   39       5       0.00              2          1
9996          516       1   35      10   57369.61              1          1
9997          709       0   36       7       0.00              1          0
9998          772       1   42       3   75075.31              2          1
9999          792       0   28       4  130142.79              1          1

      IsActiveMember  Exited  (Geography_France,)  (Geography_Germany,)  \
0                  1       1                  1.0                   0.0
1                  1       0                  0.0                   0.0
2                  0       1                  1.0                   0.0
3                  0       0                  1.0                   0.0
4                  1       0                  0.0                   0.0
...              ...     ...                  ...                   ...
9995               0       0                  1.0                   0.0
9996               1       0                  1.0                   0.0
9997               1       1                  1.0                   0.0
9998               0       1                  0.0                   1.0
9999               0       0                  1.0                   0.0

      (Geography_Spain,)
0                    0.0
1                    1.0
2                    0.0
3                    0.0
4                    1.0
...                  ...
9995                 0.0
9996                 0.0
9997                 0.0
9998                 0.0
9999                 0.0

[10000 rows x 12 columns]
0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [77]:
# Split data into training and testing set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42
)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(8000, 12)
(8000,)
(2000, 12)
(2000,)